"""Absolute Figma coordinates -> row grids that keep every position but let content grow (issues-log #65).

    node tools/evidence/measure_flow.js cache/evidence/flow-measure.json
    python tools/figma_html/flow_desktop.py      -> wp-content/themes/module11/assets/scss/base/_flow-desktop.scss

The Home layouts (and Browse by procedure) came out of the replica as `position:absolute` at Figma's y coordinates. That is
pixel-exact for the drawn copy, but a longer heading or an extra line overlaps whatever is below it. For each positioned container:
  * children are grouped into ROWS (vertical ranges that overlap belong to one row);
  * the container becomes a one-column grid, one track per row (`auto` height);
  * every child sits in its row with margin-top = its y minus the bottom of the previous row, margin-left = its x
    -> at the drawn content every element lands on the same pixel; when something grows, its row grows and pushes the rows below;
  * text boxes get min-height instead of height, media keeps its fixed box, buttons get min-width/min-height so labels can grow;
  * the container's own height becomes auto + padding-bottom (the drawn space under the last row).
Desktop only (>=1024); values in u() so it scales like the rest of the replica. Generated file: edit this script, not the SCSS.
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
MEASURE = os.path.join(ROOT, "cache", "evidence", "flow-measure.json")
OUT = os.path.join(ROOT, "wp-content", "themes", "module11", "assets", "scss", "base", "_flow-desktop.scss")


def u(v):
    v = round(v, 2)
    return "0" if abs(v) < 0.01 else f"calc({v:g} * var(--u, 1px))"


def rows_of(items):
    rows = []
    for it in sorted(items, key=lambda i: i["y"]):
        if rows and it["y"] < rows[-1]["bottom"] - 0.5:
            rows[-1]["items"].append(it)
            rows[-1]["bottom"] = max(rows[-1]["bottom"], it["y"] + it.get("h_render", it["h"]))
        else:
            rows.append({"top": it["y"], "bottom": it["y"] + it.get("h_render", it["h"]), "items": [it]})
    return rows


def main():
    data = json.load(open(MEASURE, encoding="utf-8"))
    # A converted container grows to hold its children, and in Figma some children run past their container's drawn box
    # (Browse by procedure: 215px of text in a 145px item). Rows must be built from what will RENDER, so nested containers use
    # their content extent, computed bottom-up.
    by_p = {c["P"]: c for c in data}
    memo = {}

    def extent(sel):
        if sel not in memo:
            c = by_p[sel]
            memo[sel] = max([c["H"]] + [it["y"] + eff_h(it) for it in c["items"]])
        return memo[sel]

    def eff_h(it):
        return extent(it["sel"]) if it["container"] and it["sel"] in by_p else it["h"]

    for c in data:
        for it in c["items"]:
            it["h_render"] = eff_h(it)
    out = ["// GENERATED by tools/figma_html/flow_desktop.py from measured replica geometry (tools/evidence/measure_flow.js).",
           "// Absolute Figma coordinates -> row grids: same pixels at the drawn content, content can grow (issues-log #65).",
           '@use "../abstracts/mixins" as *;', "", "@include minmedia(1024px) {"]
    sections_done = set()
    for c in data:
        scope = f".m11-page-{c['scope']}"
        rows = rows_of(c["items"])
        last = rows[-1]["bottom"] if rows else 0
        pad_b = max(0.0, c["H"] - last)
        if c["isFx"] and c["section"] not in sections_done:
            sections_done.add(c["section"])
            out.append(f"\t{scope} {c['secSel']} {{ height: auto; min-height: 0; }}")
        out.append(f"\t{scope} {c['P']} {{ display: grid; grid-template-columns: minmax(0, 1fr); align-items: start; justify-items: start; "
                   f"height: auto; min-height: 0; padding: 0 0 {u(pad_b)} 0; }}")
        for sel in c["contents"]:
            out.append(f"\t{scope} {sel} {{ display: contents; }}")
        prev_bottom = 0.0
        for r_i, r in enumerate(rows, start=1):
            for it in r["items"]:
                decl = [f"grid-row: {r_i}", "grid-column: 1", "position: relative", "inset: auto", "box-sizing: border-box",
                        f"margin: {u(it['y'] - prev_bottom)} 0 0 {u(it['x'])}"]
                if it["translate"]:
                    decl.append("transform: none")
                if it["button"]:
                    # keep the drawn width (a wider button would slide under its neighbour in the same row); let the label wrap
                    decl += [f"width: {u(it['w'])}", "height: auto", f"min-height: {u(it['h'])}", "white-space: normal"]
                elif it["media"]:
                    decl += [f"width: {u(it['w'])}", f"height: {u(it['h'])}"]
                else:
                    decl += [f"width: {u(it['w'])}", "height: auto", f"min-height: {u(it['h'])}"]
                out.append(f"\t{scope} {it['sel']} {{ {'; '.join(decl)}; }}")
            prev_bottom = r["bottom"]
    out.append("}")
    open(OUT, "w", encoding="utf-8").write("\n".join(out) + "\n")
    print(f"{len(data)} containers, {sum(len(c['items']) for c in data)} items -> {os.path.relpath(OUT, ROOT)}")


if __name__ == "__main__":
    main()
